"""Flashcards batch 2: Basic Science, English Language, Basic Technology to 15 cards per topic."""
import re
PATH = '/home/user/index.html'
s = open(PATH, encoding='utf-8').read()
def esc(t): return t.replace("\\", "\\\\").replace("'", "\\'")

CARDS = {
 # ---------------- Basic Science ----------------
 'Living Things & Health': (11, [
  ("List the seven characteristics of living things (MR NIGER D).", "Movement, Respiration, Nutrition, Irritability (sensitivity), Growth, Excretion, Reproduction and Death — non-living things may show one or two, but only living things show all."),
  ("State three differences between plants and animals.", "Plants make their own food (photosynthesis), are fixed in one place and grow throughout life; animals feed on others, move from place to place and stop growing at maturity."),
  ("What is the basic unit of all living things?", "The cell — some organisms (Amoeba, bacteria) are just one cell, while plants and animals are built of millions of specialised cells."),
  ("Arrange in order: organ, cell, tissue, system.", "Cells join to form tissues, tissues form organs (e.g. the heart), and organs work together as systems (e.g. the circulatory system) to make the whole organism."),
  ("Name the six food classes with one example of each.", "Carbohydrates (rice, yam), proteins (beans, fish, eggs), fats and oils (groundnut oil, butter), vitamins (fruits), mineral salts (vegetables, liver) and water."),
  ("What is a balanced diet?", "A meal containing all six food classes in the right proportions for a person's age and activity — it keeps the body healthy and prevents deficiency diseases."),
  ("Match each deficiency to its disease: protein, vitamin C, vitamin D, iron.", "Protein (in children): kwashiorkor; vitamin C: scurvy (bleeding gums); vitamin D: rickets (soft bent bones); iron: anaemia (tiredness, pale blood)."),
  ("Name two ways diseases are spread and one way to prevent each.", "Contaminated water/food (cholera) — drink only boiled or treated water; insect vectors — mosquitoes spread malaria, so sleep under treated nets and clear stagnant water."),
  ("Why is personal hygiene important? Give three habits.", "It prevents disease and keeps the body healthy: bathe daily, brush teeth twice a day, wash hands before eating and after the toilet, and wear clean clothes."),
  ("What is first aid, and name four items in a first aid box.", "First aid is the immediate help given to a sick or injured person before professional care: cotton wool, bandages, antiseptic, iodine, scissors, safety pins and gloves."),
  ("State two effects of lack of rest and exercise on health.", "Lack of rest causes tiredness and weakens the body's defence against disease; lack of exercise leads to weak muscles, obesity and heart problems — the body needs both sleep and activity.")
 ]),
 'Energy: Forms & Sources': (11, [
  ("Define energy.", "Energy is the ability or capacity to do work — anything that moves, heats, glows or changes needs energy."),
  ("Name six forms of energy.", "Kinetic (motion), potential (stored, by position), heat, light, sound, electrical, chemical (in food and fuels) and nuclear energy."),
  ("State the law of conservation of energy.", "Energy cannot be created or destroyed; it can only be changed from one form to another — the total energy always stays the same."),
  ("Give the energy changes in a torch, a burning candle and a battery-powered fan.", "Torch: chemical -> electrical -> light (+ heat). Candle: chemical -> heat + light. Fan: chemical/electrical -> kinetic (movement)."),
  ("What is the ultimate source of almost all energy on Earth?", "The Sun — plants store sunlight by photosynthesis, and fossil fuels, wind, rain and food chains all trace back to solar energy."),
  ("Distinguish between renewable and non-renewable sources with two examples each.", "Renewable sources never run out: sunlight, wind, flowing water (hydro). Non-renewable sources will finish: coal, petroleum, natural gas (fossil fuels)."),
  ("State three uses of solar energy in Nigeria.", "Solar panels generating electricity for homes and street lights, solar water heaters, drying crops and fish, and solar-powered calculators and phone chargers."),
  ("Name two renewable energy projects or sources used in Nigeria.", "Hydroelectric dams such as Kainji and Jebba on the River Niger, and growing solar installations; wind is used in some northern areas."),
  ("Give three ways of conserving energy at home.", "Switch off lights and appliances when not in use, use energy-saving bulbs, dry clothes in the sun instead of a dryer, and cook with lids on the pot."),
  ("What is hydroelectric power?", "Electricity generated by the energy of falling or fast-flowing water turning turbines connected to generators — a clean, renewable source."),
  ("Why is the world moving away from fossil fuels?", "They are non-renewable (they will run out) and burning them releases carbon dioxide and smoke that pollute the air and cause global warming.")
 ]),
 'Introduction to Science: Measurement & Laboratory Safety': (11, [
  ("What is measurement?", "Comparing a quantity with a standard unit to find its size, amount or degree — every measurement has a number and a unit (e.g. 5 metres)."),
  ("Give the SI unit of length, mass, time and temperature.", "Metre (m), kilogram (kg), second (s) and kelvin (K); degrees Celsius is used in everyday temperature work."),
  ("Which instrument would you use to measure: the length of a desk, the temperature of water, and 30 seconds?", "A metre rule or tape measure; a thermometer; a stopwatch (or clock)."),
  ("What is parallax error, and how do you avoid it?", "Reading a scale with the eye to one side gives a wrong value; avoid it by keeping the eye directly above the mark you are reading."),
  ("State four laboratory safety rules.", "No running or playing; never taste or smell chemicals directly; wear safety goggles and aprons when needed; report all accidents and spills to the teacher immediately."),
  ("Name four items of safety equipment in the laboratory.", "Safety goggles, fire extinguisher, first aid box, and a sand bucket — also gas taps that can be shut off quickly."),
  ("What should you do if a chemical spills on your skin?", "Wash the area immediately with plenty of clean running water and report to the teacher — never rub it in or ignore it."),
  ("How do you heat a test tube safely?", "Hold it with a test tube holder, point the mouth away from yourself and others, heat gently and move it in and out of the flame to avoid 'bumping'."),
  ("Name two derived quantities and their units.", "Area (square metres, m2) and volume (cubic metres, m3 or litres) — also density (kg/m3) and speed (m/s); derived quantities are built from the base units."),
  ("What is the difference between accuracy and estimation?", "Accuracy means the measurement is close to the true value (read instruments carefully, avoid parallax); estimation is an approximate guess made before measuring, used to check results."),
  ("How should measuring instruments be cared for?", "Clean and dry them after use, store them in their proper cases, avoid dropping them, and check for zero error before measuring.")
 ]),
 'Matter, Its Properties & Changes': (10, [
  ("Define matter and give its two basic properties.", "Matter is anything that has mass and occupies space (volume) — everything around you, including air, is matter."),
  ("Describe the particles in a solid, a liquid and a gas.", "Solid: particles packed tightly in fixed positions, vibrating only. Liquid: particles close but able to slide past one another. Gas: particles far apart, moving fast in all directions."),
  ("Distinguish between a physical change and a chemical change with one example each.", "Physical: no new substance forms and it is usually reversible (ice melting). Chemical: a new substance forms and it is usually irreversible (wood burning, iron rusting)."),
  ("Name the changes of state: solid to liquid, liquid to gas, gas to liquid, gas to solid.", "Melting, evaporation/boiling, condensation, and deposition (e.g. frost forming); solid to gas directly is sublimation (camphor, iodine)."),
  ("What is diffusion? Give one everyday example.", "The movement of particles from where they are more concentrated to where they are less concentrated — e.g. the smell of food spreading through a house, or tea colouring hot water."),
  ("Why does evaporation cause cooling?", "The most energetic particles escape from the liquid's surface, so the average energy — and the temperature — of what remains drops; that is why sweating cools the body."),
  ("Name four physical properties used to identify substances.", "Density, solubility, melting and boiling points, electrical conductivity, hardness and colour — each substance has its own set of values."),
  ("Distinguish between a mixture and a compound.", "A mixture is substances physically combined in any proportion, separable physically (sand and salt); a compound is elements chemically joined in fixed proportions, separable only chemically (water, H2O)."),
  ("Why is water called a universal solvent, and name two stages of the water cycle.", "Because more substances dissolve in it than in any other liquid. The water cycle: evaporation from seas, condensation into clouds, then precipitation (rain) — repeatedly."),
  ("Give two everyday effects of expansion and contraction of matter.", "Metal roofs and bridges need expansion gaps; overhead wires sag in heat and tighten in cold; a stuck metal lid loosens under hot water — solids, liquids and gases all expand when heated.")
 ]),
 'Acids, Bases & Salts in Everyday Life': (10, [
  ("Name an acid found in each of: oranges, vinegar and the human stomach.", "Citric acid (oranges and other citrus fruits), ethanoic/acetic acid (vinegar), and hydrochloric acid (stomach, for digesting food)."),
  ("State two properties of acids.", "They taste sour, turn blue litmus paper red, and react with metals to give hydrogen gas — handle strong acids with care because they are corrosive."),
  ("Name two common bases and one use of each.", "Soap (washing/cleaning), wood ash (traditional cleaning and making soap), slaked lime (treating acidic soil and whitewashing), milk of magnesia (relieving stomach acid)."),
  ("How does litmus paper test acids and bases?", "Blue litmus turns red in an acid; red litmus turns blue in a base; neither changes in a neutral substance like pure water or salt solution."),
  ("Name two natural indicators.", "Hibiscus (zobo) petal extract and red cabbage juice — they turn red in acids and green/blue in bases."),
  ("What does the pH scale show, and what are the values for acid, neutral and alkali?", "pH measures how acidic or alkaline a solution is, from 0 to 14: below 7 is acidic, exactly 7 is neutral, above 7 is alkaline."),
  ("Why do we take antacid medicine for stomach pain, in chemical terms?", "The medicine is a mild base that neutralises the excess hydrochloric acid in the stomach, forming a harmless salt and water — a neutralisation reaction."),
  ("Name three salts and a use of each.", "Common salt (sodium chloride) for seasoning and preserving food; Epsom salt for baths; washing soda for softening water; saltpetre (potassium nitrate) in fertilisers."),
  ("What is acid rain, and give two of its effects?", "Rain made acidic by sulphur dioxide and nitrogen oxides from factories and vehicles dissolving in it — it damages crops, kills fish in lakes, and corrodes metal roofs and painted surfaces."),
  ("Why is toothpaste used to protect teeth?", "Bacteria on teeth make acid from food sugar, which eats the enamel; toothpaste is mildly basic, so it neutralises the acid and helps prevent tooth decay.")
 ]),
 'Energy: Forms, Transformation & Simple Machines': (10, [
  ("Name the six simple machines.", "Lever, pulley, wheel and axle, inclined plane, screw and wedge."),
  ("Give the class and an example for each type of lever.", "First class: pivot in the middle — scissors, crowbar, see-saw. Second class: load in the middle — wheelbarrow, nutcracker, bottle opener. Third class: effort in the middle — tweezers, broom, the human forearm."),
  ("What is the difference between a fixed and a movable pulley?", "A fixed pulley only changes the direction of the effort (pull down to lift up); a movable pulley reduces the effort needed (mechanical advantage greater than 1)."),
  ("Why does an inclined plane make work easier?", "It lets a load be raised through the same height with less effort pushed over a longer distance — a ramp for loading drums, or winding roads up a hill."),
  ("Do machines reduce the amount of work done? Explain.", "No — they make work EASIER by reducing the effort (or changing its direction), but friction means the work input is actually a little MORE than the useful work output."),
  ("Give the energy transformation in each: a generator, photosynthesis, a loudspeaker.", "Generator: kinetic -> electrical. Photosynthesis: light -> chemical. Loudspeaker: electrical -> sound."),
  ("What is friction, and why is lubrication used in machines?", "Friction is the force opposing motion between touching surfaces; oil and grease (lubricants) form a slippery layer that reduces friction, wear and wasted heat in engines and hinges."),
  ("Give two examples of simple machines found in the human body.", "The forearm is a third-class lever (elbow is the pivot, biceps supplies the effort); the teeth act as wedges for cutting food; joints and the jaw work as levers too."),
  ("Explain the wheel and axle with one example.", "A small axle turns with a larger wheel: effort applied to the big wheel lifts a load on the axle with less force — a steering wheel, a door knob, a windlass for drawing water."),
  ("How does a bicycle use mechanisms to make riding easier?", "The chain and sprockets transfer effort from the pedals to the rear wheel; the wheel and axle multiply speed; the brakes use levers; ball bearings reduce friction in the hubs.")
 ]),
 'Human Body Systems': (11, [
  ("State three functions of the skeletal system.", "It supports the body and gives it shape, protects delicate organs (skull protects the brain, ribs protect the heart and lungs), and its joints allow movement; bones also make blood cells."),
  ("Trace the path of food through the digestive system.", "Mouth -> oesophagus (gullet) -> stomach -> small intestine (digestion and absorption) -> large intestine (water absorbed) -> rectum and anus (egestion)."),
  ("What is the function of the heart in the circulatory system?", "It is a pump that moves blood around the body: blood carries oxygen and digested food to the cells and removes carbon dioxide and other wastes."),
  ("Describe gas exchange in the respiratory system.", "Air is breathed in through the nose and windpipe to the lungs; in the tiny air sacs (alveoli) oxygen passes into the blood and carbon dioxide passes out to be breathed out."),
  ("What are the parts and functions of the nervous system?", "The brain and spinal cord (central) plus nerves (peripheral): they receive messages from sense organs, interpret them, and coordinate all body responses."),
  ("Name the organs of excretion and what each removes.", "Kidneys remove urea and excess water as urine; the skin removes water and salts as sweat; the lungs remove carbon dioxide; the liver breaks down worn-out cells and wastes."),
  ("Name the male and female reproductive organs that produce gametes.", "The testes produce sperms in males; the ovaries produce eggs (ova) in females — fertilisation joins them to begin a new life."),
  ("Name the five sense organs and what each detects.", "Eyes (light/sight), ears (sound and balance), nose (smell), tongue (taste), skin (touch, heat and pain)."),
  ("Name the four types of teeth and their functions.", "Incisors for cutting and biting, canines for tearing, premolars and molars for grinding and chewing food."),
  ("State three ways of keeping the body systems healthy.", "Eat a balanced diet, exercise regularly, rest and sleep well, bathe and keep clean, avoid smoking and alcohol, and visit the clinic for check-ups and immunisation."),
  ("What are the effects of smoking on the respiratory system?", "Smoke damages the air passages and air sacs, causing coughs, bronchitis and lung cancer; carbon monoxide in smoke also reduces the oxygen the blood can carry.")
 ]),
 'Reproduction, Growth & Drug Abuse': (10, [
  ("What is the difference between sexual and asexual reproduction?", "Sexual reproduction involves two parents (male and female gametes join), so children differ from parents; asexual involves one parent and produces identical offspring (bacteria splitting, cassava stems sprouting)."),
  ("Where does fertilisation take place in humans, and what forms?", "In the fallopian tube (oviduct): the sperm joins the egg to form a zygote, which implants in the uterus and develops into a foetus."),
  ("What is puberty?", "The stage when a child's body matures into an adult body able to reproduce — in girls it brings breast development and menstruation; in boys, voice deepening and growth of facial hair."),
  ("What is menstruation?", "The monthly flow of blood and tissue from the uterus through the vagina when an egg is not fertilised — a sign of a healthy, mature female reproductive system."),
  ("What is the difference between growth and development?", "Growth is an increase in size, height and weight (measurable); development is an increase in ability and skill — walking, talking, reasoning — over time."),
  ("What is drug abuse? Name three commonly abused substances.", "Taking drugs without medical need, in wrong amounts, or taking illegal drugs — commonly alcohol, cannabis (Indian hemp), tramadol and other prescription drugs misused for pleasure."),
  ("State three effects of drug abuse.", "Health damage (liver and brain damage, addiction, mental illness), social problems (school failure, crime, broken families), and economic loss; overdose can kill."),
  ("Why do teenagers sometimes start taking drugs, and how can it be resisted?", "Peer pressure, curiosity, stress or the desire to feel grown-up. Resist by saying no firmly, choosing friends wisely, staying busy with sport and study, and talking to trusted adults."),
  ("Name two ways HIV/AIDS is transmitted and two ways it is NOT transmitted.", "Transmitted: unprotected sex with an infected person; infected blood (shared needles, unscreened transfusion); mother to baby. NOT transmitted: hugging, sharing plates, mosquito bites, or sitting near an infected person."),
  ("Where can someone with a drug problem get help?", "Counsellors at school or clinic, hospital treatment centres, religious organisations, and government agencies like the NDLEA — asking for help early is a sign of strength, not shame.")
 ]),
 'Light, Sound & Basic Electricity': (11, [
  ("What does it mean that light travels in straight lines? Give one proof.", "Light moves in straight paths called rays — shadows with sharp edges, pinhole camera images and eclipses all prove it."),
  ("State the laws of reflection.", "The angle of incidence equals the angle of reflection, and the incident ray, reflected ray and normal all lie in one plane — this is how plane mirrors form images."),
  ("Why does a pencil look bent in a glass of water?", "Refraction: light changes speed and bends when it passes from air into water, so the submerged part appears displaced."),
  ("Name one use each of concave and convex mirrors.", "Concave: torch and headlamp reflectors, shaving/makeup mirrors (they magnify). Convex: car side mirrors and shop security mirrors (they give a wide field of view)."),
  ("What do convex and concave lenses do to light?", "A convex (converging) lens bends rays together to a focus — used in magnifying glasses and the eye; a concave (diverging) lens spreads rays apart — used in spectacles for short sight."),
  ("What is dispersion of light?", "The splitting of white light into its seven colours (red, orange, yellow, green, blue, indigo, violet) by a prism — raindrops do this to form a rainbow."),
  ("How is sound produced, and what does it need to travel?", "Sound is produced by vibrating objects and travels as waves through a medium (solid, liquid or gas) — it cannot travel through a vacuum."),
  ("Why do you see lightning before you hear thunder?", "Light travels at about 300,000 km/s while sound travels at only about 330 m/s in air, so the flash reaches you almost instantly and the thunder arrives seconds later."),
  ("Name the four parts of a simple electric circuit and two conductors and two insulators.", "A cell (source), wires, a bulb (load) and a switch. Conductors: copper and aluminium (metals generally). Insulators: rubber, plastic, dry wood."),
  ("In a series circuit of two bulbs, what happens if one bulb blows? How does a parallel circuit differ?", "In series the circuit breaks and both bulbs go out; in parallel each bulb has its own path, so the other stays lit — homes are wired in parallel for this reason."),
  ("State three electrical safety rules.", "Never touch switches or appliances with wet hands, do not overload sockets, replace damaged wires and insulation immediately, and keep water away from electrical fittings.")
 ]),
 # ---------------- English Language ----------------
 'Tenses & Subject–Verb Concord': (12, [
  ("What is the rule of concord (subject-verb agreement)?", "The verb must agree with its subject in number and person: a singular subject takes a singular verb ('The boy runs'), a plural subject takes a plural verb ('The boys run')."),
  ("Choose the correct verb: 'The list of absentees (is/are) on the board.'", "'is' — the subject is 'list' (singular), not 'absentees'; words in between do not change the subject."),
  ("Complete: 'Neither the teacher nor the students (was/were) present.'", "'were' — with neither...nor, the verb agrees with the nearer subject ('the students')."),
  ("Complete: 'Each of the boys (has/have) a textbook.'", "'has' — 'each', 'every', 'everyone' and 'nobody' are singular, even when followed by a plural noun."),
  ("When do we use the present continuous tense? Give an example.", "For actions happening now or around now: 'She is reading.' Compare the simple present for habits: 'She reads every day.'"),
  ("What is the difference between 'I have eaten' and 'I ate'?", "'I have eaten' (present perfect) links the past to the present — no finished time is stated; 'I ate' (simple past) refers to a finished time ('I ate yesterday')."),
  ("Complete with the correct form: 'By the time we arrived, the film (start) already.'", "'had started' — the past perfect is used for the earlier of two past actions."),
  ("Which collective nouns usually take singular verbs in formal writing?", "Words like 'committee', 'team', 'family', 'government' take a singular verb when acting as one unit: 'The committee has decided.'"),
  ("Choose the correct sentence: (a) The news are good. (b) The news is good.", "(b) — 'news' looks plural but is an uncountable singular noun, like 'mathematics', 'politics' and 'information'."),
  ("Complete: 'The teacher, together with his students, (is/are) going to the museum.'", "'is' — phrases like 'together with', 'along with', 'as well as' do not make the subject plural."),
  ("Rewrite in the future tense: 'They complete the project next week.'", "'They will complete the project next week' — or 'They are going to complete...' for a planned intention."),
  ("Correct the error: 'He don't like beans.'", "'He doesn't like beans' — third person singular (he, she, it) takes 'does/doesn't' in the simple present.")
 ]),
 'Idioms & Figurative Language': (11, [
  ("What is an idiom? Give an example.", "An idiom is a phrase whose meaning cannot be understood from the individual words: 'kick the bucket' means to die; 'break the ice' means to start a conversation."),
  ("What is a simile? Give an example.", "A simile compares two things using 'like' or 'as': 'He is as brave as a lion.'"),
  ("What is a metaphor? Give an example.", "A metaphor compares by saying one thing IS another (no 'like' or 'as'): 'Time is a thief.'"),
  ("What is personification? Give an example.", "Giving human qualities to non-human things: 'The wind whispered through the trees.'"),
  ("What is hyperbole? Give an example.", "Deliberate exaggeration for emphasis: 'I've told you a million times.'"),
  ("What is a euphemism? Give an example.", "A mild expression replacing a harsh one: 'He passed away' instead of 'He died'; 'between jobs' instead of 'unemployed'."),
  ("Explain the meaning of these idioms: (a) spill the beans, (b) once in a blue moon, (c) bite off more than you can chew.", "(a) Reveal a secret; (b) very rarely; (c) take on more than you can manage."),
  ("What is irony? Give an example.", "Saying or experiencing the opposite of what is expected: a fire station burns down; saying 'What lovely weather!' during a storm."),
  ("What is onomatopoeia? Give three example words.", "Words that imitate sounds: 'buzz', 'bang', 'hiss', 'cock-a-doodle-doo'."),
  ("What is alliteration? Give an example.", "Repetition of the same initial consonant sound: 'Peter Piper picked a peck of pickled peppers.'"),
  ("Interpret the proverb: 'A stitch in time saves nine.'", "Dealing with a problem early (one stitch now) prevents it from growing into a much bigger problem (nine stitches later) — act before trouble multiplies.")
 ]),
 'Punctuation & Capitalisation': (12, [
  ("When do you use a full stop, a question mark and an exclamation mark?", "Full stop ends a statement; question mark ends a question; exclamation mark shows strong feeling or a command shouted: 'What a goal!'"),
  ("Give three uses of the comma.", "Separating items in a list ('rice, beans and yam'), after an introduction ('However, we stayed.'), and to join two complete sentences with a conjunction ('She sang, and he danced')."),
  ("What is the difference between a colon and a semicolon?", "A colon introduces a list or explanation ('Bring: a pen, a biro and a ruler.'); a semicolon joins two closely related complete sentences without a conjunction ('Rain fell; the match was cancelled.')."),
  ("When do you use an apostrophe for possession, and where does it go with plurals?", "Singular: the boy's bag (apostrophe + s). Plural ending in s: the boys' bags (apostrophe after the s). Plural not ending in s: the children's toys."),
  ("Explain the difference between 'its' and 'it's'.", "'Its' shows possession ('The dog wagged its tail'); 'it's' is short for 'it is' or 'it has' ('It's raining'). Test: if 'it is' fits, use it's."),
  ("List five kinds of words that must begin with capital letters.", "The first word of a sentence, proper nouns (names of people, places: Ada, Lagos), days and months (Monday, June), titles of books and people (Mr Okonkwo), the pronoun 'I', and names of languages and nationalities."),
  ("Punctuate correctly: come here she said", "'Come here,' she said. — opening capital, comma inside the quotation marks, and a full stop at the end."),
  ("When is a hyphen used? Give two examples.", "To join parts of compound words: 'mother-in-law', 'well-known', 'twenty-one'."),
  ("What is a run-on sentence, and how can it be fixed?", "Two sentences joined with no punctuation ('I came I saw'). Fix it with a full stop, a semicolon, or a comma plus conjunction ('I came, and I saw.')."),
  ("How do you punctuate the date and addresses in a formal letter?", "Date: day month year with a comma pattern like '10th September, 2026.' The writer's address ends each line with a comma (open punctuation) or none — but be consistent, and the letter ends with a comma after 'Yours faithfully'."),
  ("Punctuate: my uncle lives in abuja nigeria", "My uncle lives in Abuja, Nigeria. — capital for the sentence start and each proper noun, comma between city and country, full stop at the end."),
  ("When are quotation marks (inverted commas) used?", "To enclose the exact words spoken or written by someone: 'I will come tomorrow,' she promised. Also for titles of short works like poems and articles.")
 ]),
 'Comprehension & Summary Writing': (12, [
  ("What is the difference between skimming and scanning?", "Skimming is reading quickly for the general idea; scanning is searching for a specific detail (a name, date or figure) — use both before answering comprehension questions."),
  ("How do you find the main idea of a passage?", "Look at the title, the topic sentence of each paragraph (often the first sentence) and any repeated words — the main idea is what the whole passage is mostly about."),
  ("What is an inference question?", "One whose answer is not stated directly — you must 'read between the lines' and draw a conclusion from clues in the passage."),
  ("How do you answer a 'what does the word X mean as used in the passage?' question?", "Give the meaning that fits the context, not just any dictionary meaning — test your answer by replacing the word in the sentence."),
  ("What does a reference question ask? Give an example.", "What a pronoun or phrase points back to: 'The boy dropped the cup and it broke' — 'it' refers to the cup."),
  ("State four rules of good summary writing.", "Use your own words; keep only the main points (drop examples, illustrations and repetition); stick to the required number of sentences; and write in correct grammar without adding new ideas."),
  ("What must you never do when writing a summary?", "Never copy whole sentences from the passage, never add your own opinion or outside information, and never exceed the number of sentences or words required."),
  ("How do you identify the writer's purpose in a passage?", "Ask: is the writer informing (giving facts), persuading (arguing a view), entertaining (telling a story) or describing? The purpose shapes the tone and word choice."),
  ("How should you answer True/False comprehension questions?", "Judge strictly by the passage — not by general knowledge; if the passage does not say it, it is not 'true according to the passage'."),
  ("What is a topic sentence?", "The sentence that states the main idea of a paragraph; the other sentences give supporting details, examples or evidence."),
  ("Why should comprehension answers be written in full sentences?", "Examiners award marks for complete, grammatical answers that repeat the question's key words — one-word answers often lose marks even when correct."),
  ("What does the writer's tone mean? Give examples of tone words.", "Tone is the writer's attitude shown through word choice: serious, humorous, critical, admiring, angry or sympathetic.")
 ]),
 'Synonyms, Antonyms & Word Formation': (12, [
  ("What is a synonym? Give three pairs.", "A word with the same or nearly the same meaning as another: big/large, begin/commence, happy/joyful."),
  ("What is an antonym? Give three pairs.", "A word opposite in meaning: ancient/modern, expand/contract, victory/defeat."),
  ("In 'nearest in meaning' questions, what is the golden rule?", "Test each option by substituting it into the original sentence — the best synonym must keep the sentence's meaning unchanged."),
  ("Add a prefix to make the opposite: (a) happy, (b) agree, (c) place, (d) behave.", "(a) unhappy; (b) disagree; (c) displace; (d) misbehave — common negative prefixes: un-, dis-, in-/im-, mis-, non-."),
  ("What does the suffix '-ful' mean? Give two examples.", "'Full of': beautiful (full of beauty), careful (full of care). Its opposite is '-less': careless (without care)."),
  ("Form the noun from each verb: decide, inform, agree, govern.", "Decision, information, agreement, government — word formation changes a word's class while keeping its core meaning."),
  ("Give the word family of 'active'.", "act (verb), active (adjective), actively (adverb), activity (noun), inactivity (negative noun) — knowing families helps in cloze and summary questions."),
  ("Distinguish between homophones with an example set.", "Homophones sound the same but differ in spelling and meaning: 'their/there/they're', 'peace/piece', 'write/right'."),
  ("Choose the correct word: 'The new law will (affect/effect) all students.'", "'affect' — affect is usually the verb (to influence); effect is usually the noun (the result): 'The law will have an effect.'"),
  ("What are collocations? Give two examples.", "Words that naturally go together: 'make a mistake' (not 'do a mistake'), 'heavy rain' (not 'strong rain') — collocations mark natural, native-like English."),
  ("Form the adjective: nation, comfort, depend, fame.", "National, comfortable, dependable (dependent), famous."),
  ("Find the odd one out: joyful, cheerful, elated, miserable.", "'Miserable' — the other three are synonyms meaning very happy; miserable is the antonym.")
 ]),
 'Essay & Letter Writing': (12, [
  ("Name the four main types of essay.", "Narrative (telling a story), descriptive (painting a picture in words), expository (explaining and informing), and argumentative/persuasive (arguing a position)."),
  ("What are the three essential parts of every essay?", "Introduction (introduce the topic), body (develop your points in paragraphs — one main idea per paragraph), and conclusion (sum up and give a final thought)."),
  ("List the features of a formal letter.", "Writer's address and date; receiver's designation and address; formal salutation 'Dear Sir/Madam'; a heading/title for the subject; formal tone; closing 'Yours faithfully' with signature and full name."),
  ("How does an informal letter differ from a formal letter?", "One address (the writer's) and date; a friendly salutation ('Dear Ada'); casual, warm language; no title needed; it closes 'Yours sincerely' (or 'Your friend') with the first name only."),
  ("What is the correct salutation and closing for a letter to a principal you do not know?", "Salutation: 'Dear Sir/Madam' (or 'The Principal' as designation); closing: 'Yours faithfully,' followed by signature and full name."),
  ("Why is planning (an outline) important before writing an essay?", "An outline organises your points, keeps paragraphs focused, ensures you answer the actual question, and prevents repetition and running out of time."),
  ("In an argumentative essay, why should you mention the other side's view?", "Refuting the opposing view shows balance and strengthens your argument — 'Some people say X, however...' makes your position more convincing."),
  ("What is paragraph unity?", "Every sentence in a paragraph must support that paragraph's single main idea; a new idea means a new paragraph."),
  ("How is an essay marked in WAEC/NECO? Name the four criteria.", "Content (relevant ideas), Organisation (structure and flow), Expression (vocabulary, grammar, sentence variety), and Mechanical Accuracy (spelling, punctuation, capitalisation)."),
  ("Give two useful opening phrases for a formal letter of complaint.", "'I am writing to express my dissatisfaction with...' and 'I wish to draw your attention to...' — state the purpose in the first paragraph."),
  ("What should the title/heading of a formal letter look like?", "A short subject line in capital letters or underlined, e.g. 'COMPLAINT ABOUT POOR WATER SUPPLY' — placed after the salutation."),
  ("Name three common essay errors that cost marks.", "Not answering the question asked; one giant paragraph with no structure; careless tense shifts and agreement errors — proofread before you finish.")
 ]),
 'Sentence Types, Clauses & Phrases': (12, [
  ("Name the four sentence types by function with an example of each.", "Declarative/statement ('She sings.'), interrogative/question ('Does she sing?'), imperative/command ('Sing!'), exclamatory ('What a song!')."),
  ("What is the difference between a simple and a compound sentence?", "A simple sentence has one independent clause ('The bell rang.'); a compound sentence joins two independent clauses with a conjunction: 'The bell rang, and the pupils rushed out.'"),
  ("What is a complex sentence? Give an example.", "One independent clause plus at least one dependent (subordinate) clause: 'Because the rain stopped, we played outside.' The dependent clause cannot stand alone."),
  ("What is a clause, and how does it differ from a phrase?", "A clause has a subject and a verb ('when he came'); a phrase is a group of related words without both ('in the morning', 'the tall boy')."),
  ("Identify the clause type: 'I know that he is honest.'", "'that he is honest' is a noun clause — it acts as the object of 'know' (answers 'know what?')."),
  ("Identify the clause type: 'The boy who won the race is my cousin.'", "'who won the race' is an adjective (relative) clause — it describes 'the boy', introduced by the relative pronoun 'who'."),
  ("Identify the clause type: 'She left before the film ended.'", "'before the film ended' is an adverb clause — it tells WHEN she left, introduced by the subordinating conjunction 'before'."),
  ("Name the seven coordinating conjunctions.", "FANBOYS: For, And, Nor, But, Or, Yet, So — they join equal grammatical parts."),
  ("List four subordinating conjunctions.", "because, although, if, when (also since, unless, while, before, after) — they introduce dependent clauses."),
  ("Convert to a complex sentence: 'He was tired. He finished the work.'", "'Although he was tired, he finished the work.' — the subordinating conjunction turns one clause into a dependent clause."),
  ("What is a sentence fragment? Give an example and a fix.", "An incomplete sentence lacking a subject, verb or complete thought: 'Because he was tired.' Fix: attach it to a main clause — 'He left early because he was tired.'"),
  ("Identify the phrase type: 'The girl in the blue dress is my sister.'", "'in the blue dress' is a prepositional phrase acting as an adjective — it identifies which girl.")
 ]),
 'Direct & Indirect (Reported) Speech': (12, [
  ("What is the difference between direct and indirect speech?", "Direct speech repeats the exact words in quotation marks ('I am tired,' he said); indirect speech reports the meaning without quotes (He said that he was tired)."),
  ("What happens to the verb tense when reporting a statement made in the past?", "It shifts one step back: present -> past ('I am' -> he was), past -> past perfect ('I ate' -> he had eaten), will -> would, can -> could, must -> had to."),
  ("Convert: 'I am waiting for you,' she said.", "She said that she was waiting for me — the pronouns change as well as the tense."),
  ("How do time and place words change in reported speech?", "now -> then, today -> that day, yesterday -> the day before, tomorrow -> the next day, here -> there, this -> that, ago -> before."),
  ("How do you report a yes/no question?", "Use asked + whether/if, statement word order, and no question mark: 'Are you ready?' -> He asked whether I was ready."),
  ("How do you report a wh-question?", "Keep the question word but use statement order: 'Where do you live?' -> She asked where I lived (NOT 'where did I live')."),
  ("How do you report commands and requests?", "Use told/ordered/requested + object + to-infinitive: 'Shut the door,' he said -> He told me to shut the door. Negatives: 'Don't run' -> He told us not to run."),
  ("How do you report an exclamation?", "Use 'exclaimed' with the feeling named: 'What a beautiful dress!' -> She exclaimed with admiration that the dress was beautiful."),
  ("What is the difference between 'said' and 'told'?", "'Told' needs a person object (He told ME...); 'said' does not (He said that...). Never 'He said me'."),
  ("Which reporting verbs suit advice, warning and promise?", "advised ('You should rest' -> He advised me to rest), warned ('Don't touch it' -> She warned us not to touch it), promised ('I will help' -> He promised to help)."),
  ("Does the tense change when reporting a universal truth?", "No — general truths stay in the present: 'Water boils at 100 degC,' the teacher said -> The teacher said that water boils at 100 degC."),
  ("Convert: 'I bought this book yesterday,' Ada said.", "Ada said that she had bought that book the day before.")
 ]),
 'Phrasal Verbs, Prepositions & Register': (12, [
  ("What is a phrasal verb? Give two examples.", "A verb combined with a particle (adverb or preposition) to create a new meaning: 'give up' = quit, 'look after' = take care of."),
  ("Give the meaning of: (a) put off, (b) break down, (c) run into, (d) turn down.", "(a) postpone; (b) stop working (a machine); (c) meet by chance; (d) reject."),
  ("What is the difference between 'look for' and 'look after'?", "'Look for' means to search ('I'm looking for my pen'); 'look after' means to take care of ('She looks after her brother') — the particle changes everything."),
  ("Choose the correct preposition: 'The meeting is (in/on/at) Monday (in/on/at) 9 a.m.'", "'on Monday' (days take 'on') and 'at 9 a.m.' (clock times take 'at'); months and years take 'in' (in June, in 2026)."),
  ("Give the correct preposition for: afraid, interested, good, congratulate, married.", "afraid OF, interested IN, good AT, congratulate ON, married TO — these fixed pairings must be memorised."),
  ("What is register?", "The level of formality of language suited to a situation: formal ('The ceremony will commence at noon'), neutral ('The event starts at twelve'), informal ('It kicks off at twelve')."),
  ("Give a formal and an informal word for: begin, buy, apologise, sufficient.", "begin/commence; buy/purchase; apologise/apologise formally vs 'say sorry'; enough/sufficient — formal words suit essays and official letters."),
  ("Why is 'The car broke down on the expressway' better understood than 'The car died'?", "'Broke down' is the conventional phrasal verb for a vehicle ceasing to work; precise register and idiom prevent misunderstanding."),
  ("Correct the preposition: 'He is suffering from headache since Monday.'", "'He has been suffering from a headache since Monday' — 'since' needs the present perfect continuous, and 'headache' takes the article 'a'."),
  ("Complete with a phrasal verb: 'The thieves (escaped with) the money' -> use 'made ... with'.", "'The thieves made off with the money' — 'make off with' means to steal and escape with something."),
  ("Choose the right register: 'Kindly (a) drop or (b) submit your scripts.' — which for an exam notice?", "(b) submit — official notices use formal register; 'drop' is casual spoken English."),
  ("What does 'call off' mean? Use it in a sentence.", "To cancel: 'The school called off the match because of rain.'")
 ]),
 'Literary Appreciation: Prose, Drama & Poetry': (12, [
  ("Name the three genres of literature with an example form of each.", "Prose (novels, short stories — e.g. Things Fall Apart), drama (plays — e.g. The Lion and the Jewel), and poetry (poems — e.g. 'The Piano and Drums')."),
  ("Name the five main elements of prose fiction.", "Plot (the sequence of events), character, setting (time and place), theme (the central idea), and point of view (who tells the story)."),
  ("Who are the protagonist and antagonist?", "The protagonist is the main character the story centres on; the antagonist opposes the protagonist — the source of the story's central conflict."),
  ("What is the difference between tragedy and comedy in drama?", "Tragedy ends in disaster for the hero, often through a fatal flaw (e.g. pride); comedy ends happily, often in marriage or reconciliation, and mocks human weaknesses with humour."),
  ("What is a stanza, and what is a rhyme scheme?", "A stanza is a group of lines in a poem (like a paragraph); the rhyme scheme is the pattern of end rhymes, written with letters — ABAB means lines 1 and 3 rhyme, and 2 and 4 rhyme."),
  ("Identify the device: 'The angry sky roared.'", "Personification — the sky is given human qualities (anger, roaring). If it were 'the sky roared like a lion', it would be a simile."),
  ("What is the difference between theme and moral?", "The theme is the central idea or subject explored (e.g. betrayal); the moral is the lesson the writer wants the reader to learn (e.g. 'pride comes before a fall')."),
  ("Distinguish between flat and round characters.", "Flat characters are simple and unchanging (a cruel stepmother); round characters are complex and develop through the story — they change as events affect them."),
  ("Name three types of conflict in literature.", "Man against man (rivalry), man against nature (a storm, an animal), man against himself (inner doubt or fear), and man against society (rebellion against custom)."),
  ("What are flashback and foreshadowing?", "Flashback interrupts the story to show earlier events; foreshadowing drops hints about what will happen later, building suspense."),
  ("What is dramatic irony?", "When the audience knows something a character does not — we watch a character walk into a trap we can see coming; it creates tension or humour."),
  ("How should you answer an appreciation question on a poetic device?", "Identify the device, quote the exact line, then explain its EFFECT — what picture, feeling or idea it creates ('The simile compares X to Y, suggesting...').")
 ]),
 'Sentence Structure & Composition': (10, [
  ("What is a sentence?", "A group of words that expresses a complete thought, containing at least a subject and a verb, and beginning with a capital letter and ending with a full stop."),
  ("Identify the subject and predicate in: 'The little girl sang a song.'", "Subject: 'The little girl' (who the sentence is about); predicate: 'sang a song' (what is said about the subject)."),
  ("Name the four kinds of sentences by use.", "Statements, questions, commands and exclamations — each with its own end punctuation."),
  ("Join into one sentence with 'but': 'Musa studied hard. He failed the test.'", "'Musa studied hard, but he failed the test.' — 'but' joins opposite ideas; 'and' joins similar ones; 'because' shows reason."),
  ("Why must every sentence have a verb? Spot the error: 'The tall man in the black coat.'", "A verb shows the action or state — this is a fragment (no verb). Fix: 'The tall man wore a black coat.'"),
  ("Expand this sentence with an adjective and an adverb: 'The dog barked.'", "'The fierce dog barked loudly.' — adjectives describe nouns, adverbs describe verbs, making writing vivid."),
  ("What is a paragraph, and what makes a good one?", "A group of sentences about ONE idea, marked by an indent or a line space; a good paragraph has a topic sentence, supporting sentences and a clear ending."),
  ("Name four linking words that order a composition.", "First, next, then, after that, finally (also: however, therefore, meanwhile) — they guide the reader through your ideas."),
  ("Plan a composition: 'My Best Friend'. What points would you include?", "Who the friend is and how we met; physical description; character and qualities; things we do together; why I value the friendship — one point per paragraph."),
  ("State three rules for good composition writing.", "Answer the exact question asked; organise into an introduction, body and conclusion; use correct punctuation, capitalisation and tenses — and always leave time to proofread.")
 ]),
 'Oral English: Vowels, Consonants & Stress': (10, [
  ("Roughly how many vowel and consonant sounds does English have?", "About 20 vowel sounds (including diphthongs) and 24 consonant sounds — far more sounds than the 26 letters of the alphabet, which is why spelling and sound differ."),
  ("What is the difference between long and short vowels? Give a pair.", "Long vowels are held longer: /i:/ in 'sheep' vs the short /I/ in 'ship'; also /u:/ 'pool' vs /U/ 'pull' — confusing them changes the word."),
  ("Give two pairs of consonant sounds Nigerians often mix up.", "/p/ and /b/ ('pat' vs 'bat'), /f/ and /p/ ('fan' vs 'pan'), and /θ/ (think) pronounced as /t/ or /f/ — practise the pairs to hear the difference."),
  ("What is a diphthong? Give two examples.", "A glide between two vowel sounds in one syllable: /ei/ in 'face', /ou/ in 'goat', /ai/ in 'price', /au/ in 'mouth'."),
  ("What is word stress, and why does it matter?", "Word stress is the emphasis on one syllable of a word: 'PHOtograph', 'phoTOGraphy'. Wrong stress can make a word unrecognisable to listeners."),
  ("How does stress distinguish these noun/verb pairs: PREsent vs preSENT?", "The noun is stressed on the first syllable ('a PREsent', 'a REcord'); the verb on the second ('to preSENT', 'to reCORD') — stress changes the word class."),
  ("Name three words with silent letters.", "'knee' (silent k), 'knife' (silent k), 'listen' (silent t), 'comb' (silent b), 'island' (silent s)."),
  ("What is sentence stress?", "Emphasising the important words (nouns, main verbs) in a sentence while weak forms glide over small words: 'The BOY ate the RICE.'"),
  ("What is intonation?", "The rise and fall of the voice in speech — falling tone for statements and wh-questions ('Where are you going?'), rising tone for yes/no questions ('Are you ready?')."),
  ("What is a minimal pair? Give an example.", "Two words differing by only one sound: 'ship/sheep', 'full/fool', 'cot/caught' — minimal-pair drills sharpen pronunciation.")
 ]),
 'Comprehension & Summary Basics': (10, [
  ("Should you read the questions or the passage first? Why?", "A good strategy: skim the passage quickly, read the questions so you know what to hunt for, then re-read the passage carefully — this saves time and focuses your search."),
  ("How do you answer a question whose answer is stated directly in the passage?", "Locate the exact sentence (scan for key words from the question), then restate the answer in your own words as a complete sentence."),
  ("How can you guess the meaning of a new word in a passage?", "Use context clues: look at the rest of the sentence, examples given, contrast words like 'but' or 'however', and the word's general sense — then check your guess fits the sentence."),
  ("Why must summary answers use your own words?", "Copying whole sentences from the passage loses marks; the examiner is testing whether you understood and can restate the idea briefly and accurately."),
  ("In a summary, what kind of content should you leave out?", "Examples, illustrations, comparisons, repetition, names/dates used as evidence, and any personal opinion — keep only the main points."),
  ("How do you find the main idea of a passage quickly?", "Check the title, the first and last paragraphs, and the topic sentence of each paragraph — then ask: 'What is this mostly about?'"),
  ("How should you answer a True/False question safely?", "Rely only on the passage; if it does not state the fact, do not use outside knowledge — write True/False exactly as the question demands, sometimes with your reason."),
  ("What makes a good title for a passage?", "A short phrase naming the central subject — not too broad ('Life') and not too narrow ('One Farmer's Goat'); it should cover the whole passage."),
  ("How should you use the instruction 'Answer in one sentence'?", "Combine the required points into ONE grammatically correct sentence — two correct points in one sentence score; one point per sentence when told 'one sentence per point'."),
  ("Why is punctuation and capitalisation important in comprehension answers?", "They are marked under mechanical accuracy: begin with a capital, end with a full stop, and punctuate correctly — careless mechanics cost easy marks.")
 ]),
 'Parts of Speech': (11, [
  ("Name the eight parts of speech.", "Noun, pronoun, verb, adjective, adverb, preposition, conjunction and interjection."),
  ("What is a noun? Name four types.", "A noun names a person, place, thing or idea. Types: common (boy, city), proper (Ada, Kano — capitalised), abstract (love, courage), collective (team, flock), and countable/uncountable (chair/water)."),
  ("What is a pronoun? Give five examples.", "A word used in place of a noun to avoid repetition: he, she, it, they, we (personal); this, those (demonstrative); who, which (relative)."),
  ("What is a verb? Distinguish action and linking verbs.", "A verb expresses action or state. Action verbs show doing ('She ran'); linking verbs connect the subject to a description — be, seem, become ('She is happy'). Helping (auxiliary) verbs assist: is, have, will."),
  ("What is an adjective? Give an example in a sentence.", "An adjective describes or modifies a noun: 'The TALL boy won.' — it answers 'which one?' or 'what kind?'"),
  ("What is an adverb? Give an example.", "An adverb modifies a verb, adjective or another adverb, telling how, when, where or how much: 'She sang SWEETLY', 'He arrived YESTERDAY'."),
  ("What is a preposition? Give five examples.", "A word showing the relationship (often position or time) between a noun/pronoun and other words: in, on, under, beside, after."),
  ("What is a conjunction? Give four examples.", "A word that joins words, phrases or sentences: and, but, or, because."),
  ("What is an interjection? Give three examples.", "A word or short phrase expressing sudden feeling, usually followed by an exclamation mark: 'Wow!', 'Oh!', 'Alas!'"),
  ("Identify the parts of speech in: 'The old man walked slowly into the market.'", "The (article/adjective), old (adjective), man (noun), walked (verb), slowly (adverb), into (preposition), the (article), market (noun)."),
  ("Choose the correct word: 'She is a (quick/quickly) runner.' and 'He runs (quick/quickly).'", "'quick' (adjective describing the noun 'runner'); 'quickly' (adverb describing the verb 'runs') — adjectives modify nouns, adverbs modify verbs.")
 ]),
 'Verb Tenses Made Simple': (10, [
  ("When do we use the simple present tense? Give an example.", "For habits, routines and general truths: 'She goes to school every day.' 'Water boils at 100 degC.'"),
  ("When do we use the present continuous? Give an example.", "For actions happening now or these days: 'I am reading a book.' 'He is staying with us this week.'"),
  ("How is the simple past formed? Give regular and irregular examples.", "Regular verbs add -ed ('walked', 'played'); irregular verbs change form: go-went, eat-ate, see-saw, write-wrote, buy-bought."),
  ("When do we use the past continuous? Give an example.", "For an action in progress at a past moment, often interrupted: 'We were eating when the light went off.'"),
  ("What is the present perfect and when is it used?", "have/has + past participle: for past actions with present results or unfinished time: 'I have finished my homework.' 'She has lived here since 2020.'"),
  ("Give three ways of expressing the future with an example each.", "'will' for decisions/predictions ('I will help you'); 'going to' for plans ('We are going to travel'); present continuous for fixed arrangements ('I am leaving tomorrow')."),
  ("What are tense signal words? Match: always, now, yesterday, since, tomorrow.", "always -> simple present; now -> present continuous; yesterday -> simple past; since -> present perfect; tomorrow -> future."),
  ("Correct: 'Yesterday I go to the market.'", "'Yesterday I went to the market' — 'yesterday' forces the simple past of 'go'."),
  ("Complete: 'While she (cook), the phone (ring).'", "'While she was cooking, the phone rang.' — past continuous for the longer background action, simple past for the interrupting one."),
  ("Why must tenses stay consistent in a story?", "Shifting tenses confuses the reader: a narrative told in the past should continue in the past ('He woke up and washed...'), except for direct speech or universal truths.")
 ]),
 'Summary Writing & précis': (10, [
  ("What is a précis?", "A clear, short restatement of a passage's main points in your own words, keeping the original's meaning and order but dropping everything non-essential."),
  ("State four golden rules of précis writing.", "Use your own words; keep only main ideas; stay within the required length; and add nothing new — no opinions, no outside facts."),
  ("What kinds of material should be cut when writing a précis?", "Examples and illustrations, statistics used as evidence, repetitions, comparisons and descriptive details, names and quotations — unless the instruction says to keep them."),
  ("How do you handle a passage that gives three examples after each point?", "State the point once and drop the examples — the précis reports the claim, not the evidence."),
  ("Should a précis be written in the first person?", "No — keep the writer's perspective in third person and avoid 'I think'; you are reporting the passage, not reacting to it."),
  ("What is the recommended working method for a précis question?", "Read the passage fully; underline the topic sentence of each paragraph; draft one sentence per required point; count your words; then rewrite neatly within the limit."),
  ("If asked to 'summarise in three sentences', how many points may you give?", "Exactly three main points, one per sentence — four points in three sentences means one point is lost or two are crammed together (and penalised)."),
  ("Why is grammatical accuracy part of précis marks?", "The summary is marked on expression and mechanical accuracy: fragments, run-ons and agreement errors cost marks even when the content is right."),
  ("Turn this into one précis sentence: 'Many students fail because they do not plan. They start reading only the night before the exam. They sleep late and come tired.'", "Poor planning — especially last-minute, late-night reading — causes many students to fail. (One idea, own words, no examples.)"),
  ("What is the difference between a summary and a précis?", "In school practice they overlap; strictly, a précis keeps the original's structure and proportion in a fixed fraction of its length, while a summary may condense more freely — both demand the main points in your own words.")
 ]),
 # ---------------- Basic Technology ----------------
 'Technology in Everyday Life': (12, [
  ("Define technology.", "Technology is the application of scientific knowledge, skills and tools to solve human problems and make life easier — from a simple matchet to a computer."),
  ("Give four examples of technology used in the Nigerian home.", "Blenders and gas cookers, refrigerators, mobile phones, televisions, generators and solar lamps."),
  ("What is the difference between developed and underdeveloped technology?", "Developed technology uses advanced machines and power (tractors, computers); underdeveloped (indigenous) technology relies on simple hand tools and human effort (hoe, local loom) — both solve problems at different scales."),
  ("State three advantages of technology.", "Work is done faster and with less effort; communication and transport are quicker; medicine and food production improve, raising the quality of life."),
  ("State three disadvantages or dangers of technology.", "Pollution from factories and vehicles; machines replacing some jobs (unemployment); accidents and health problems from misuse; and over-dependence (e.g. phone addiction)."),
  ("Name three examples of indigenous Nigerian technology.", "The local loom for weaving (aso-oke, akwete), blacksmithing of hoes and knives, pottery firing, and palm-oil processing with local presses."),
  ("List the steps of the technological/design process.", "Identify the need or problem, gather information, plan/design, make/construct the solution, test and evaluate it, then improve it."),
  ("How has technology improved communication? Give three examples.", "Mobile phones and the internet give instant calls, messaging and email; radio and television broadcast information; satellites link the whole world in real time."),
  ("How does technology improve agriculture? Give three examples.", "Tractors plough far faster than hoes; improved seeds and fertilisers raise yields; irrigation supplies water in the dry season, and machines process harvests quickly."),
  ("Name three careers that depend on technology.", "Engineering (mechanical, electrical, civil), information technology (programming, networking), medical technology (scanning, laboratory equipment), and architecture."),
  ("Why is safety important when using technology?", "Machines, electricity and chemicals can injure or kill if misused — instructions, guards, protective clothing and correct handling prevent accidents."),
  ("How can technology help Nigeria develop? Give two examples.", "Better technology raises production and creates wealth (mechanised farming, factories) and improves services (online banking, e-learning, telemedicine) — driving economic growth.")
 ]),
 'Common Tools & Their Uses': (11, [
  ("Classify hand tools into five groups with one example each.", "Cutting (saw, chisel, knife), driving (hammer, screwdriver), measuring (tape, rule, try square), holding (bench vice, pliers, G-clamp) and boring (hand drill)."),
  ("What is a try square used for?", "Testing and marking right angles (squareness) on wood and metal, and marking straight lines across a workpiece."),
  ("Name two types of screwdriver and their matching screws.", "The flat-head (single slot) and the Phillips (star/cross-head) screwdriver — each must match its screw head to avoid damaging it."),
  ("Which saw cuts metal, and which cuts wood across the grain?", "A hacksaw cuts metal; a cross-cut saw cuts wood across the grain (a rip saw cuts along the grain; a tenon saw, with its stiff back, cuts precise joints)."),
  ("What is a bench vice used for?", "Holding work firmly on the workbench while it is cut, filed or hammered, so both hands are free and the work cannot slip."),
  ("Name three measuring tools and what each measures.", "Steel rule (short straight lengths), tape measure (long lengths and curves), calipers (internal/external diameters), try square (squareness), protractor (angles)."),
  ("State four ways of caring for hand tools.", "Clean them after use, oil metal parts to prevent rust, store them in a toolbox or on a rack (not on the floor), and repair or replace damaged handles immediately."),
  ("State three safety rules when using hand tools.", "Use each tool only for its proper purpose, keep cutting edges sharp (dull tools slip), carry sharp tools pointing downwards, and never use tools with broken handles."),
  ("What is the difference between a spanner and a wrench?", "Both turn nuts and bolts; a spanner is made to fit standard nut sizes (ring or open-jaw), while an adjustable wrench (monkey wrench) can be set to many sizes."),
  ("Which tool would you use to: (a) draw out a nail, (b) drill a small hole, (c) smooth rough wood?", "(a) Claw hammer or pincers; (b) hand drill or power drill; (c) a plane, then sandpaper."),
  ("Why should you choose the right tool for each job?", "The right tool works faster and more accurately, keeps you safe, and avoids damaging the tool and the workpiece — using a screwdriver as a chisel ruins both.")
 ]),
 'Technical Drawing: Instruments, Lines & Lettering': (8, [
  ("Name five drawing instruments and one use of each.", "T-square (horizontal lines), set squares (vertical and inclined lines), compass (circles and arcs), divider (transferring measurements), protractor (angles), and pencils for lines."),
  ("What is the T-square used for, and how is it held?", "Drawing horizontal lines and supporting set squares — its head slides along the left edge of the board; always draw from left to right along the top edge of the blade."),
  ("State the angles of the two set squares and two angles they can produce together.", "45-45-90 and 30-60-90 set squares; used alone they give 30, 45, 60 and 90 deg lines, and combined they give 15 and 75 deg lines."),
  ("Describe the line types used in technical drawing: visible edges, hidden details, and centre lines.", "Visible outlines: continuous THICK lines; hidden details: short dashes; centre lines: alternating long and short dashes; dimension lines: thin continuous lines with arrowheads."),
  ("What is lettering in technical drawing, and what makes it good?", "The printing of notes, titles and dimensions in single-stroke, uniform CAPITAL letters along guidelines — even height, spacing and slope make drawings easy to read."),
  ("What information goes in the title block?", "The drawing title, the draughtsman's name, the date, the scale used, the drawing number, and the projection symbol — usually in the bottom right corner."),
  ("What do pencil grades H, HB and B mean?", "H pencils are hard (light, sharp lines for construction), B are soft (dark lines for outlines), and HB is between them — the higher the number, the harder or blacker."),
  ("What is drawing scale, and give an example.", "Scale is the ratio of the drawing size to the real size: 1:1 (full size), 1:50 (reduction — 1 cm represents 50 cm) or 2:1 (enlargement).")
 ]),
 'Safety in the Workshop': (10, [
  ("What is workshop safety?", "All the rules, habits and equipment that prevent accidents and injuries while working — safety is everybody's responsibility, every time."),
  ("Name four items of personal protective equipment (PPE).", "Safety goggles (eyes), apron/overalls (body), safety boots (feet), gloves (hands), and a nose mask where there is dust or fumes."),
  ("State four causes of workshop accidents.", "Carelessness and horseplay, using faulty or wrong tools, slippery or cluttered floors, loose clothing near machines, and tiredness or rushing."),
  ("State four workshop safety rules.", "No running or playing; keep tools in their places after use; report damaged tools and spills at once; do not operate machines you have not been trained on; keep aisles clear."),
  ("What is first aid? Name four contents of a first aid box.", "First aid is immediate help given before medical care arrives: bandages, cotton wool, antiseptic solution, iodine, scissors, plasters and gloves."),
  ("What should you do if a workshop accident happens?", "Stay calm, stop work nearby, give first aid only if trained, report to the teacher/supervisor immediately, and record the accident — never move a seriously injured person unnecessarily."),
  ("Name two classes of fire and the correct extinguisher for an electrical fire.", "Fires are classed by fuel: solids (wood, paper — water), flammable liquids (petrol — foam or dry powder), and electrical fires — use a CO2 or dry-powder extinguisher, NEVER water."),
  ("Why must machines have guards, and clothing be fitted?", "Guards cover moving parts (belts, blades) so hands cannot be caught; loose sleeves, ties or jewellery can be pulled into rotating parts — wear fitted clothes and tie back long hair."),
  ("What is good housekeeping in the workshop, and why does it matter?", "Keeping the workplace clean, dry and organised: sawdust and oil cause slips, clutter causes trips, and stored tools prevent damage — most accidents are housekeeping failures."),
  ("Give three electrical safety rules for the workshop.", "Do not touch equipment with wet hands, check cables for damage before use, switch off and unplug machines before adjusting them, and never overload sockets.")
 ]),
 'Geometrical Construction & Plane Figures': (11, [
  ("How do you bisect a line segment with compasses?", "With the compass opened more than half the line, draw arcs above and below from each end; join the two arc crossings — the line cuts the segment into two equal halves at 90 deg."),
  ("How do you bisect an angle?", "From the vertex, strike an arc cutting both arms; from those two points, strike equal arcs that cross inside the angle; join the vertex to the crossing point."),
  ("How is a 60 deg angle constructed?", "Draw a base line; from a point on it, draw an arc; keeping the same radius, step the arc across itself from the crossing point; join the vertex to that mark — an equilateral-triangle angle."),
  ("How do you construct a 90 deg angle, then 45 and 30 deg?", "Construct the perpendicular (90 deg) by arcs from points on the line; bisect the 90 deg angle for 45 deg; bisect the 60 deg angle for 30 deg — bisection halves any constructed angle."),
  ("How do you construct a triangle given its three sides (SSS)?", "Draw the base to scale; with the compass set to each of the other sides, strike arcs from the base ends; the arcs cross at the third vertex — join to complete the triangle."),
  ("Construct a regular hexagon in a circle. Why does it work?", "With the compass set to the circle's radius, step six arcs round the circumference and join them — each side equals the radius, since a hexagon splits into six equilateral triangles."),
  ("How do you divide a line into equal parts (say five)?", "Draw a sloping ray from one end; mark five equal compass steps along it; join the last mark to the line's end, then draw parallels through the other marks — they cut the line into five equal parts."),
  ("How do you construct an equilateral triangle of side 6 cm?", "Draw a 6 cm base; with the compass at 6 cm, strike arcs from both ends; the crossing point is the third vertex — all sides and angles (60 deg) are equal."),
  ("How do you draw a line parallel to a given line through a point?", "Use a set square and T-square: align the square's edge with the line, hold the T-square against the square, slide the square until its edge meets the point, then draw — or copy an angle (corresponding angles)."),
  ("What is the relationship between the radius and diameter of a circle, and its circumference formula?", "Diameter = 2 x radius; circumference = 2πr (= πd); area = πr^2."),
  ("Why must pencils be sharp and compasses tight for good constructions?", "Blunt pencils make thick, uncertain lines and tight compasses keep the radius exact — construction accuracy depends on fine lines and fixed radii.")
 ]),
 'Building Materials & Simple Structures': (10, [
  ("Name six common building materials.", "Sand, granite/gravel, cement, blocks or bricks, iron rods (reinforcement), timber, zinc roofing sheets, water, nails and paint."),
  ("What is concrete, and what role does each ingredient play?", "A mix of cement (binder), sand and gravel (aggregate, for strength and bulk) and water (activates the cement). Iron rods inside it (reinforced concrete) add tensile strength."),
  ("What is the function of a building's foundation?", "It spreads the building's load safely onto the ground, prevents uneven settlement and rising damp — a weak foundation cracks the whole structure."),
  ("Name three roofing materials and one advantage of each.", "Zinc/aluminium sheets (light, quick to fix, cheap), clay tiles (durable, cool, attractive), and asbestos-free fibre sheets or thatch (cheap, local — thatch is cool but flammable)."),
  ("State four properties of good building materials.", "Strength (carries load without failing), durability (lasts against weather and wear), workability (can be shaped), and reasonable cost; also resistance to fire and water where needed."),
  ("What is a lintel, and where is it placed?", "A beam of concrete or steel placed across the top of a door or window opening to carry the wall load above it."),
  ("Name three traditional/local building materials in Nigeria.", "Mud/adobe (moulded earth walls), thatch (palm-frond roofs), laterite, bamboo and raffia palm — cheap and cool, though less durable than modern materials."),
  ("Why do builders cure concrete by wetting it for days after casting?", "Cement hardens by a chemical reaction with water (hydration); keeping the fresh concrete wet lets it cure fully, so it reaches its proper strength without cracking."),
  ("Name four fasteners used in construction and carpentry.", "Nails, wood screws, bolts and nuts, and rivets — each chosen for the material and the strength needed."),
  ("State three ways of maintaining a building.", "Paint woodwork and metal to keep out water, repair leaking roofs and cracked walls quickly, keep gutters and drains clear, and check electrical wiring — regular care prevents costly damage.")
 ]),
 'Machines, Mechanisms & Maintenance': (12, [
  ("Define a machine.", "A device that makes work easier by changing the size or direction of the effort force — it never reduces the total work done, because friction wastes some energy."),
  ("Name four types of motion with an example each.", "Rotary/rotational (a fan blade), reciprocating (a sewing machine needle), linear (a sliding door), and oscillating (a pendulum or windscreen wiper)."),
  ("What is a mechanism? Give three examples.", "A combination of machine parts that transmits or controls motion: gears, belt and pulley drives, chain and sprockets, linkages, cams and cranks."),
  ("How do gears work, and what are the driver and driven gears?", "Interlocking teeth pass rotary motion from one gear to another; the gear supplying the motion is the driver, the one receiving it is the driven — a small driver turning a large driven gear reduces speed but increases turning force."),
  ("Explain the chain and sprocket system on a bicycle.", "Pedal cranks turn the front sprocket; the chain transfers the motion to the rear sprocket on the wheel — changing sprocket sizes changes how far one pedal turn drives the bike."),
  ("What is the purpose of bearings in machines?", "Bearings (ball or roller) replace sliding friction with rolling friction at rotating joints, so shafts spin smoothly with less wear, heat and energy loss."),
  ("Name the three main types of maintenance.", "Routine/corrective maintenance (cleaning, oiling, fixing faults as they appear), preventive/scheduled maintenance (planned servicing before failure), and breakdown maintenance (repair after failure — the most costly)."),
  ("Why is lubrication important in machines?", "Oil and grease reduce friction between moving parts, so machines waste less energy, run cooler, wear out slowly and last longer."),
  ("Identify the mechanisms in a bicycle (four of them).", "Wheel and axle (wheels), chain and sprocket (drive), levers (brakes and pedals), screw (bolts and seat adjustment), and bearings in the hubs."),
  ("Name four machine fasteners.", "Bolts and nuts, screws, rivets, and keys/pins — fasteners hold machine parts together and allow dismantling for repair."),
  ("State three consequences of poor maintenance.", "Machines break down often and cost more to repair, accidents rise as parts wear (brakes, guards), fuel and energy are wasted, and the machine's life is shortened."),
  ("Give two examples of machines in a Nigerian home and the mechanisms they use.", "A blender (electric motor with gears/blades rotating at speed) and a sewing machine (foot pedal lever, belt drive, reciprocating needle mechanism).")
 ])
}

ins = 0
for title, (need, pairs) in CARDS.items():
    assert len(pairs) >= need, title
    m = re.findall(r"\n(\s*)title: '" + re.escape(title) + r"',", s)
    assert len(m) == 1, ('anchor', title, len(m))
    ind = m[0]
    pos = s.index("\n" + ind + "title: '" + title + "',")
    j = s.index('cards: [', pos)
    k = s.index('\n', j) + 1
    body = ''.join((ind + "  { q: '%s', a: '%s' },\n" % (esc(q), esc(a))) for q, a in pairs[:need])
    s = s[:k] + body + s[k:]
    ins += need

open(PATH, 'w', encoding='utf-8').write(s)
print('Basic Science + English + Basic Tech: inserted', ins, 'cards')
